### ISSUE TITLE
Customized optimizer

### ISSUE THREAD

**Issue by cswpy** [slideflow/slideflow#262]
## Feature

Support for customized optimizers during training allows for greater flexibility in training models. Some frameworks in WSI tasks consist of multiple networks. Right now, we can only build a model with a single network.

## Pitch

There are some models that require customized optimizers, typically models that are consisted of several modules. For example, [WENO](https://github.com/miccaiif/WENO/tree/main) is consisted of a student network and a teacher network. Right now, I cannot implement WENO using SlideFlow.

## Alternatives

I don't think the current version has support for such knowledge distillation network.

**Comment by jamesdolezal** [comment]
Thanks for this suggestion. At present, Slideflow could be used for image processing and preparation of feature bags (in PyTorch format) for external, customized MIL training loops like WENO. I will look into whether we can extend our MIL training framework to add support for custom optimizers. I don't think it would take too much work.
