### ISSUE TITLE
ctranspath for feature extraction still gives error in 2.3.2

### ISSUE THREAD

**Issue by Meijian** [slideflow/slideflow#406]
## Description

I have installed slideflow 2.3.2 and tried to extract features with ctranspath, but it still gives: 'int' object is not subscriptable error. I'm using timm 1.0.8.

## To Reproduce
1.
from slideflow.model import build_feature_extractor
exm = build_feature_extractor('ctranspath', tile_px=299)

2. features = sf.DatasetFeatures(exm, dataset=dataset)

### Full error message

TypeError: 'int' object is not subscriptable
File <command-2206128926937267>, line 1
----> 1 features = sf.DatasetFeatures(exm, dataset=dataset)
      2 features.to_torch(rootpath + 'ctranspath' +'/bag_directory/')
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/features.py:237, in DatasetFeatures.__init__(self, model, dataset, labels, cache, annotations, **kwargs)
    235 # Otherwise will need to generate new activations from a given model
    236 elif model is not None:
--> 237     self._generate_features(cache=cache, **kwargs)
    239 # Now delete slides not included in our filtered TFRecord list
    240 loaded_slides = list(self.activations.keys())
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/features.py:479, in DatasetFeatures._generate_features(self, cache, progress, verbose, pool_sort, pb, **kwargs)
    476 # Calculate final layer activations for each tfrecord
    477 fla_start_time = time.time()
--> 479 activations, predictions, locations, uncertainty = fg.generate(
    480     progress=progress, pb=pb, verbose=verbose
    481 )
    483 self.activations = {s: np.stack(v) for s, v in activations.items()}
    484 self.predictions = {s: np.stack(v) for s, v in predictions.items()}
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/features.py:1737, in _FeatureGenerator.generate(self, verbose, progress, pb)
   1735 with sf.util.cleanup_progress((pb if progress else None)):
   1736     for batch_img, _, batch_slides, batch_loc_x, batch_loc_y in dataset:
-> 1737         model_output = self._calculate_feature_batch(batch_img)
   1738         q.put((model_output, batch_slides, (batch_loc_x, batch_loc_y)))
   1739         if pb:
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/features.py:1370, in _FeatureGenerator._calculate_feature_batch(self, batch_img)
   1365         if self.has_torch_gpu_normalizer():
   1366             batch_img = self.normalizer.preprocess(
   1367                 batch_img.to(self.normalizer.device),
   1368                 standardize=self.standardize
   1369             ).to(self.device)
-> 1370         return self.generator(batch_img)
   1371 else:
   1372     if self.has_torch_gpu_normalizer():
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/extractors/_factory_torch.py:171, in TorchFeatureExtractor.__call__(self, obj, **kwargs)
    169 if self.channels_last:
    170     obj = obj.to(memory_format=torch.channels_last)
--> 171 return self.model(obj)
File /databricks/python/lib/python3.10/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/extractors/ctranspath.py:528, in SwinTransformer.forward(self, x)
    527 def forward(self, x):
--> 528     x = self.forward_features(x)
    529     x = self.head(x)
    530     return x
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/extractors/ctranspath.py:521, in SwinTransformer.forward_features(self, x)
    519     x = x + self.absolute_pos_embed
    520 x = self.pos_drop(x)
--> 521 x = self.layers(x)
    522 x = self.norm(x)  # B L C
    523 x = self.avgpool(x.transpose(1, 2))  # B C 1
File /databricks/python/lib/python3.10/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []
File /databricks/python/lib/python3.10/site-packages/torch/nn/modules/container.py:217, in Sequential.forward(self, input)
    215 def forward(self, input):
    216     for module in self:
--> 217         input = module(input)
    218     return input
File /databricks/python/lib/python3.10/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/extractors/ctranspath.py:400, in BasicLayer.forward(self, x)
    398         x = checkpoint.checkpoint(blk, x)
    399     else:
--> 400         x = blk(x)
    401 if self.downsample is not None:
    402     x = self.downsample(x)
File /databricks/python/lib/python3.10/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/extractors/ctranspath.py:286, in SwinTransformerBlock.forward(self, x)
    284 # merge windows
    285 attn_windows = attn_windows.view(-1, self.window_size, self.window_size, C)
--> 286 shifted_x = window_reverse(attn_windows, self.window_size, H, W)  # B H' W' C
    288 # reverse cyclic shift
    289 if self.shift_size > 0:
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/timm/models/swin_transformer.py:75, in window_reverse(windows, window_size, H, W)
     64 """
     65 Args:
     66     windows: (num_windows*B, window_size, window_size, C)
   (...)
     72     x: (B, H, W, C)
     73 """
     74 C = windows.shape[-1]
---> 75 x = windows.view(-1, H // window_size[0], W // window_size[1], window_size[0], window_size[1], C)
     76 x = x.permute(0, 1, 3, 2, 4, 5).contiguous().view(-1, H, W, C)
     77 return x

## Expected behavior

It should extract features without a problem.

## Environment:

 - Slideflow Version (e.g., 1.0): 2.3.2
 - OS (e.g., Ubuntu): Ubuntu 22.04.4 LTS
 - How you installed Slideflow (`pip`, source): pip
 - Python version: 3.10
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information: timm: 1.0.8

**Comment by jamesdolezal** [comment]
Shoot! Sorry about that. It was fixed, but it seems the fix was reverted in a bad merge. I pushed an update to `master`.

Version 3.0 is on its way out the door, so I'm not going to bother pushing an another patch fix to PIP. 

Sorry about the inconvenience.

**Comment by Meijian** [comment]
Great! Thank you for the update. Do you have a rough timeline for version 3.0 release? I can't wait to try it out.

**Comment by jamesdolezal** [comment]
Aiming for mid next week. I'm writing the release notes and updating the docs now.

**Comment by Meijian** [comment]
Perfect! Looking forward to it!

**Comment by jamesdolezal** [comment]
Fixed with version 3.0
