### ISSUE TITLE
slideflow 3.0 gives error when loading project

### ISSUE THREAD

**Issue by Meijian** [slideflow/slideflow#411]
## Description

First, congrats on the release of 3.0.
I installed slideflow 3.0.0 and tried to load a preexisting project that I have been working on. It gave an error: AttributeError: module 'slideflow' has no attribute 'util'. I'd appreciate any suggestions! Thanks!

## To Reproduce
1. import slideflow as sf
import os
os.environ['SF_BACKEND'] = 'torch'
os.environ['SF_SLIDE_BACKEND'] = 'cucim'
os.environ['SF_ALLOW_ZIP'] = '0'
3. rootpath = '/path-to-project/'
4. P = sf.load_project(rootpath)

Full error message:
AttributeError: module 'slideflow' has no attribute 'util'
File <command-2206128926937265>, line 2
      1 rootpath='/dbfs/mnt/gmb-ds-dbpoc/megu/hnsc/'
----> 2 P = sf.load_project(rootpath)
      3 P.annotations=rootpath+"annotation_TCGA_Tempus.csv"
      4 dataset=P.dataset(tile_px=299, tile_um='10x')
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/project.py:3712, in load(root, **kwargs)
   3702 def load(root: str, **kwargs) -> "Project":
   3703     """Load a project at the given root directory.
   3704 
   3705     Args:
   (...)
   3710 
   3711     """
-> 3712     return Project(root, **kwargs)
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/project.py:99, in Project.__init__(self, root, use_neptune, create, **kwargs)
     59 """Load or create a project at a given directory.
     60 
     61 If a project does not exist at the given root directory, one can be
   (...)
     96 
     97 """
     98 self.root = root
---> 99 if sf.util.is_project(root) and kwargs:
    100     raise errors.ProjectError(f"Project already exists at {root}")
    101 elif sf.util.is_project(root):

## Environment:

 - Slideflow Version (e.g., 1.0): 3.0.0
 - OS (e.g., Ubuntu): Ubuntu
 - How you installed Slideflow (`pip`, source): pip
 - Python version: 3.10
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by jamesdolezal** [comment]
First guess is that you're in a directory that contains a folder named "slideflow", which causes Python to try to import "slideflow.util" from that folder instead of where it should be importing from.

Can you try changing directory to a new location and seeing if the error persists?

**Comment by Meijian** [comment]
You are right, there was a file named slideflow.log. I deleted it and the error is gone. Closing it now.

**Comment by jamesdolezal** [comment]
Glad to hear it! Keep us posted if you encounter any other issues with 3.0.

**Comment by Meijian** [comment]
Yes, I will! Thanks.
