### ISSUE TITLE
[BUG] Resnet50 model load error when used as a feature extractor in Slideflow3.0.0

### ISSUE THREAD

**Issue by ShihuiZhu** [slideflow/slideflow#412]
## Description
After updating to slideflow3.0, I've run into a error when trying to load the config of the `resnet50_imagnet` model. I've used the same code as I used before for previous versions so I think this issue is with the 3.0 version only.

Error as shown below:

```
...
Downloading: "https://download.pytorch.org/models/resnet50-11ad3fa6.pth" to /home/.cache/torch/hub/checkpoints/resnet50-11ad3fa6.pth
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 97.8M/97.8M [00:04<00:00, 25.0MB/s]
[18:01:13] INFO     Using resnet50_imagenet as the extractor, info: Compose(                                                                            
                        Lambda()                                                                                                                        
                        Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225))                                                                
                    )                                                                                                                                   
Traceback (most recent call last):
  File "/home/projects/histo_project/slideflow_functions.py", line 234, in tile_encoding
    P.generate_feature_bags(
  File "/home/.conda/envs/slideflow3/lib/python3.9/site-packages/slideflow/project_utils.py", line 42, in _impl
    return _filters_to_dataset(obj, method, model, *args, dataset=dataset, **kwargs)
  File "/home/.conda/envs/slideflow3/lib/python3.9/site-packages/slideflow/project_utils.py", line 56, in _filters_to_dataset
    config = sf.util.get_model_config(model)
  File "/home/.conda/envs/slideflow3/lib/python3.9/site-packages/slideflow/util/__init__.py", line 986, in get_model_config
    if model_path.endswith('params.json'):
AttributeError: 'TorchImagenetLayerExtractor' object has no attribute 'endswith'
```

## To Reproduce
```
#...dataset loading
extractor = build_feature_extractor(
        "resnet50_imagenet", 
        tile_px=256,
        backend='torch',
    )
# ... feature extraction
```

## Expected behavior
The model should be loaded for feature extraction

## Environment:

 - Slideflow Version: 3.0.0
 - OS: linux
 - How you installed Slideflow: pip
 - Python version: 3.9.19
 - CUDA/cuDNN version: cupy-cuda11x 13.2.0
 - GPU models and configuration: Tesla V100-PCIE-16GB

**Comment by jamesdolezal** [comment]
Thanks for the report! I just pushed the fix. In the meantime, you can work around this error by using `Dataset.generate_feature_bags()` instead of `Project.generate_feature_bags()`:

Instead of:

```python
P.generate_feature_bags(extractor, dataset=dataset, ...)
```
do
```python
dataset.generate_feature_bags(extractor, ...)
```

Additionally, I see you're using the `tile_px=256` keyword argument for the feature extractor. As a heads up, this keyword argument was removed in 3.0 and replaced with more explicit options for image preprocessing ([see the docs](https://slideflow.dev/features/#image-preprocessing)). The old behavior in version 2.0 was to center crop images that did not match the input image size; to maintain the same behavior as 2.0, you should do:

```python
extractor = build_feature_extractor(..., center_crop=True)
```

But you now have more options, such as resizing (or cropping + resizing), specifying the interpolation and/or anti-aliasing, etc. This change was made to facilitate clarity in what's happening to the images before they're sent to the feature extractor.

**Comment by ShihuiZhu** [comment]
Hi! Thank you for the quick fix :) Regarding the new `build_feature_extractor` function, I've tried to use it with `resnet50_imagenet` model but it gives me an error:
```
[17:56:08] INFO     Feature extractor resnet50_imagenet available in both Tensorflow and PyTorch backends; using active backend torch                   
Traceback (most recent call last):
  File "/projects/histo_project/slideflow_functions.py", line 216, in tile_encoding
    extractor = build_feature_extractor(
  File "/home/.conda/envs/slideflow3/lib/python3.9/site-packages/slideflow/model/extractors/_factory.py", line 166, in build_feature_extractor
    return build_torch_feature_extractor(name, **kwargs)
  File "/home/.conda/envs/slideflow3/lib/python3.9/site-packages/slideflow/model/extractors/_factory_torch.py", line 19, in build_torch_feature_extractor
    return _torch_extractors[name](**kwargs)
TypeError: resnet50_imagenet() missing 1 required positional argument: 'tile_px'
```

Code I've used:
```
extractor = build_feature_extractor(
       "resnet50_imagenet", 
        resize=256,  # resize to 256
        center_crop=True, # to the size of the input feature
        antialias=False,
    )
```

But it works fine when I try to load other new feature extractors virchow/gigapath. Looks like the bug is with the resnet50 model only. For now I'm using the old definition for resnet50.
