### ISSUE TITLE
[BUG] docker image not found

### ISSUE THREAD

**Issue by vgainullin** [slideflow/slideflow#424]
## Description
Readme points to missing docker image
## To Reproduce

1. docker pull slideflow/slideflow:latest-tf

Error response from daemon: pull access denied for slideflow/slideflow, repository does not exist or may require 'docker login'

## Expected behavior

docker downloads image

**Comment by jamesdolezal** [comment]
Sorry about this! The correct docker hub address is `jamesdolezal/slideflow`. We had intended to migrate to an organization account at `slideflow/slideflow`, but with the sunsetting of free Docker Team accounts, we decided to keep the repository hosted on a free personal account. 

I've updated our documentation and README accordingly.
