### ISSUE TITLE
keyboard shortcuts for slideflow-studio

### ISSUE THREAD

**Issue by zhangguy** [slideflow/slideflow#425]
Hi, 

My slides have a lot of letters and labels in the scanned image. Sometimes the tissue area itself is small and tile extraction followed by Gaussian + Otsu do not yield a lot of tiles. If I make a ROI, the number of tiles will increase dramatically.

I have a lot of slides to go through (hundreds). If shortcuts for "open the next slide in the project" and "Add ROI (Freehand)" exist, it'll improve the speed of making ROIs. Is it something realistic to implement? Thanks!

**Comment by jamesdolezal** [comment]
These shortcuts actually already exist, although I do not believe we have explicitly mentioned them anywhere in the docs. They are:

- *Open next slide*: <Ctrl> + <right arrow>
- *Add free-hand ROI*: A
- *Add polygon ROI*: P
- *Edit ROIs*: E
- *Save ROIs*: <Ctr> + S
- *Exit ROI editing*: A, or <Esc>

**Comment by zhangguy** [comment]
Thanks!
