### ISSUE TITLE
Slideflow 3.0.1 for Docker

### ISSUE THREAD

**Issue by andrewvalesano** [slideflow/slideflow#426]
Will version 3 be made available for installation via Docker? Looks like the most recent update on Docker Hub was 2.2.1 last year (https://hub.docker.com/r/jamesdolezal/slideflow). Thank you!

**Comment by jamesdolezal** [comment]
Yes - the Docker images are going through an update now, and should be posted shortly!

**Comment by jamesdolezal** [comment]
Updated docker images for 3.0.2 are [now live](https://hub.docker.com/r/jamesdolezal/slideflow/tags)
